spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: true
      settings.web-allow-others: true
  datasource:
    url: jdbc:h2:mem:ui-backend-db;NON_KEYWORDS=user
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-only
    show-sql: true
    defer-datasource-initialization: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
#  jpa:
#    defer-datasource-initialization:
#      true
#    hibernate:
#      ddl-auto: create
#      show-sql: true