#spring:
#  datasource:
#    driverClassName: 'org.postgresql.Driver'
##    url: 'jdbc:postgresql://localhost:5433/OverridetechUsers'
#    url: 'jdbc:postgresql://localhost:5433/Overridetech'
#    username: 'postgres'
#    password: 'admin'
##  mvc:
##    hiddenmethod:
##      filter:
##        enabled: true
#  jpa:
#    hibernate:
#      ddl-auto: update
#      show-sql: true
#
##dadata:
##  apiToken: ${APIKey}
##  secretKey: ${secretKey}
spring:
  liquibase:
    enabled: true
    change-log: classpath:liquibase-outputChangeLog.yml
dadata:
  apiToken: ${dadata_APIKey}
  secretKey: ${dadata_secretKey}


#logging:
#  level:
#    org:
#      springframework:
#        web: TRACE
#      hibernate: TRACE

#//working config!
#logging.logstash:
#  enabled: true
#  url: 194.87.237.197:50000