spring:
  datasource:
    driverClassName: 'org.postgresql.Driver'
    url: 'jdbc:postgresql://localhost:5433/OverridetechUsers'
    username: 'postgres'
    password: 'admin'

  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true