services:
  server:
    image: 'server-image'
    build:
      context: .
    container_name: 'server-container'
    ports:
      - 8081:8080
    depends_on:
      - db
#        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database-container:5432/Overridetech
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_JPA_HIBERNATE_SHOW_SQL=true
      - dadata_apiToken=${dadata_APIKey}
      - dadata_secretKey=${dadata_secretKey}
#    env_file:
#      - variables.env
  db:
    image: postgres:latest
    container_name: 'database-container'
#    user: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=Overridetech
    ports:
      - 5435:5432
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready", "--quiet" ]
#      interval: 1s
#      timeout: 5s
#      retries: 10
