# name: Build & Deploy

on:
  push:
    branches:
      - master

jobs:
  build_jar:
    name: Build java jar package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: 
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven and copy jar to docker folder
        run: |
          mvn clean package -B --file pom.xml -DskipTests=true
          cp ./target/task231-0.0.1-SNAPSHOT.jar ./src/main/docker
          
      # - name: build docker image
      #   run: |
      #     cd ./src/main/docker
      #     docker image build -t server-image:latest .
      #     docker images
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Server Build and Push to Dockerhub
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_TOKEN }}/server-image
