# name: Build & Deploy

on:
  push:
    branches:
      - master

jobs:
  main_job:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - uses: actions/setup-java@v4
      #   with: 
      #     java-version: '11'
      #     distribution: 'temurin'
      #     cache: 'maven'

      # - name: Build with Maven and copy jar to docker folder
      #   run: |
      #     mvn clean package -B --file pom.xml -DskipTests=true
      #     cp ./target/task231-0.0.1-SNAPSHOT.jar ./src/main/docker
      #     # cd ./src/main/docker
      #     # ls
          
      # # - name: build docker image
      # #   run: |
      # #     cd ./src/main/docker
      # #     docker image build -t server-image:latest .
      # #     docker images
      # - name: Login to DockerHub
      #   uses: docker/login-action@v3.1.0
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3.2.0
      
      # - name: Server Build and Push to Dockerhub
      #   uses: docker/build-push-action@v5.3.0
      #   with:
      #     file: ./src/main/docker/Dockerfile
      #     push: true
      #     tags: dockeruser7234/server-image

      
      - name: Copy Starting Files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # source: "./src/main/docker/.env,./src/main/docker/docker-compose.yml"
          source: "./actions_test.txt"
          target: "/home/vladislav/"
          overwrite: true
      

        
      # - name: Ssh Connect
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USERNAME }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     port: 22
      #     script: |
      #       docker stop server-container
      #       docker rm server-container
      #       docker rmi dockeruser7234/server-image
      #       ls
      #       docker ps
      #       docker images
